# Generated by Django 6.0.3 on 2026-04-17 15:02

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scan_type', models.CharField(choices=[('OPG', 'OPG (Orthopantomogram)'), ('IOPA', 'IOPA (Intraoral Periapical)')], max_length=4)),
                ('original_image', models.ImageField(upload_to=core.models.scan_image_upload_path)),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to=core.models.annotated_image_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged')], default='pending', max_length=12)),
                ('inference_time_ms', models.FloatField(blank=True, help_text='Model inference time in milliseconds', null=True)),
                ('model_version', models.CharField(default='YOLOv8-dental-v1', max_length=50)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.patient')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence score 0.0 to 1.0')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6)),
                ('bbox_x1', models.FloatField(default=0)),
                ('bbox_y1', models.FloatField(default=0)),
                ('bbox_x2', models.FloatField(default=0)),
                ('bbox_y2', models.FloatField(default=0)),
                ('fdi_tooth_number', models.IntegerField(blank=True, help_text='FDI notation tooth number', null=True)),
                ('landmarks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.scan')),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='ScanComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='core.patient')),
                ('scan_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_as_after', to='core.scan')),
                ('scan_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_as_before', to='core.scan')),
            ],
            options={
                'verbose_name': 'Scan Comparison',
                'ordering': ['-created_at'],
            },
        ),
    ]
