# Generated by Django 6.0.3 on 2026-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='crown_present',
            field=models.BooleanField(default=False, help_text='Crown detected on same tooth region'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='disease_under_crown',
            field=models.BooleanField(default=False, help_text='Disease detected underneath a crown'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='filling_present',
            field=models.BooleanField(default=False, help_text='Filling detected on same tooth region'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='secondary_caries',
            field=models.BooleanField(default=False, help_text='Secondary caries detected around a filling'),
        ),
    ]
