# Generated by Django 6.0.3 on 2026-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detectionresult_crown_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
