# Generated by Django 6.0.3 on 2026-07-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=6),
        ),
        migrations.AlterField(
            model_name='scan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=12),
        ),
    ]
