# Generated by Django 6.0.3 on 2026-07-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='annotated_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='original_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
